// Cognito Configuration - Auto-generated by Terraform
const COGNITO_CONFIG = {
    userPoolId: 'eu-west-1_13fKTZw4o',
    clientId: '2ggi07dd8s63p3469j59t82p0o',
    region: 'eu-west-1',
    identityPoolId: 'eu-west-1:ce94d110-cb76-4acf-8f1a-5e2ce8588ae2',
    domain: 'https://cert-management-dev-secure-9xeyqp04.auth.eu-west-1.amazoncognito.com'
};

// Initialize Amazon Cognito
const poolData = {
    UserPoolId: COGNITO_CONFIG.userPoolId,
    ClientId: COGNITO_CONFIG.clientId
};

let userPool;
let cognitoUser;

// Initialize on page load
if (typeof AmazonCognitoIdentity !== 'undefined') {
    userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
}

// Check if user is authenticated
function isAuthenticated() {
    const cognitoUser = userPool.getCurrentUser();
    
    if (cognitoUser != null) {
        return new Promise((resolve, reject) => {
            cognitoUser.getSession((err, session) => {
                if (err) {
                    reject(err);
                    return;
                }
                resolve(session.isValid());
            });
        });
    }
    return Promise.resolve(false);
}

// Get current user info
function getCurrentUser() {
    const cognitoUser = userPool.getCurrentUser();
    
    if (cognitoUser != null) {
        return new Promise((resolve, reject) => {
            cognitoUser.getSession((err, session) => {
                if (err) {
                    reject(err);
                    return;
                }
                
                cognitoUser.getUserAttributes((err, attributes) => {
                    if (err) {
                        reject(err);
                        return;
                    }
                    
                    const userInfo = {
                        username: cognitoUser.getUsername(),
                        email: attributes.find(attr => attr.Name === 'email')?.Value,
                        name: attributes.find(attr => attr.Name === 'name')?.Value,
                        groups: session.getAccessToken().payload['cognito:groups'] || []
                    };
                    
                    resolve(userInfo);
                });
            });
        });
    }
    return Promise.resolve(null);
}

// Get ID token for API calls
function getIdToken() {
    const cognitoUser = userPool.getCurrentUser();
    
    if (cognitoUser != null) {
        return new Promise((resolve, reject) => {
            cognitoUser.getSession((err, session) => {
                if (err) {
                    reject(err);
                    return;
                }
                resolve(session.getIdToken().getJwtToken());
            });
        });
    }
    return Promise.resolve(null);
}

// Sign in user
function signIn(email, password) {
    const authenticationData = {
        Username: email,
        Password: password
    };
    
    const authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(authenticationData);
    
    const userData = {
        Username: email,
        Pool: userPool
    };
    
    const cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
    
    return new Promise((resolve, reject) => {
        cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: (result) => {
                resolve(result);
            },
            onFailure: (err) => {
                reject(err);
            },
            newPasswordRequired: (userAttributes, requiredAttributes) => {
                // User needs to set a new password
                reject({ message: 'New password required', code: 'NEW_PASSWORD_REQUIRED', userAttributes, requiredAttributes, cognitoUser });
            }
        });
    });
}

// Change password (for first-time login)
function changePassword(cognitoUser, newPassword, userAttributes) {
    return new Promise((resolve, reject) => {
        // CRITICAL: Pass ONLY an empty object to avoid "Cannot modify an already provided email" error
        // Cognito automatically retains all existing attributes when you pass {}
        // DO NOT pass email, email_verified, sub, or any other attributes
        
        console.log('Changing password with empty attributes object');
        
        // Always pass empty object - Cognito will preserve all existing user attributes
        cognitoUser.completeNewPasswordChallenge(newPassword, {}, {
            onSuccess: (result) => {
                console.log('Password change successful');
                resolve(result);
            },
            onFailure: (err) => {
                console.error('Password change failed:', err);
                reject(err);
            }
        });
    });
}

// Sign out user
function signOut() {
    const cognitoUser = userPool.getCurrentUser();
    if (cognitoUser != null) {
        cognitoUser.signOut();
    }
    window.location.href = '/login.html';
}

// Protect page - redirect to login if not authenticated
async function protectPage() {
    try {
        const authenticated = await isAuthenticated();
        if (!authenticated) {
            window.location.href = '/login.html';
        }
    } catch (error) {
        console.error('Authentication check failed:', error);
        window.location.href = '/login.html';
    }
}

// Check permissions
async function hasPermission(requiredGroup) {
    try {
        const user = await getCurrentUser();
        if (!user) return false;
        
        const userGroups = user.groups || [];
        
        // Admins have all permissions
        if (userGroups.includes('Admins')) return true;
        
        // Check for specific group
        if (requiredGroup && userGroups.includes(requiredGroup)) return true;
        
        return false;
    } catch (error) {
        console.error('Permission check failed:', error);
        return false;
    }
}
